# Generated by Django 2.1.7 on 2019-03-20 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rss_24sata', '0002_auto_20190316_1135'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='channel',
            field=models.CharField(default='channel', max_length=100),
        ),
    ]
